[package]
name = "sched"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]

[dependencies]
xnor_llist = { git = "https://github.com/x37v/rust-llist", branch = "develop" }
spinlock = { git = "https://github.com/x37v/rust-spinlock-mutex", branch = "develop" }

[dev-dependencies]
jack = { git = "https://github.com/RustAudio/rust-jack.git" }
euclidian-rythms = { git = "https://github.com/x37v/euclidian-rythm.git"}
rosc = "~0.1"
