[package]
name = "sched"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[features]
std = ["lazy_static", "rand"]
euclidean = ["euclidian-rythms"]
default = ["std", "euclidean"]

[dependencies]
sched_macros = { git = "https://github.com/x37v/sched_macros.git" }
rand = { version = "0.7.3", default-features = true, optional = true }
num = { version = "0.3.1", default-features = false }
euclidian-rythms = { git = "https://github.com/x37v/euclidian-rythm.git", optional = true }
libc = "0.2.80"
cfg-if = "1.0.0"
lazy_static = { version = "1.4.0", optional = true }
spin = "0.7.0"

[dev-dependencies]
jack = { git = "https://github.com/RustAudio/rust-jack.git" }
rosc = "0.4.2"
heapless = "0.5.6"
assert_approx_eq = "1.1.0"

[[example]]
name = "jack-client"
#required-features = ["std", "euclidean"]

#[[example]]
#name = "no_std"

#XXX for the no_std test, remove when not needed anymore
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


