[package]
name = "sched"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[features]
std = [ "xnor_llist", "failure", "alloc"]
alloc = []
euclidean = ["euclidian-rythms"]
default = ["std", "euclidean"]

[dependencies]
sched_macros = { git = "https://github.com/x37v/sched_macros.git" }
xnor_llist = { git = "https://github.com/x37v/rust-llist", branch = "develop", optional = true }
rand = { version = "0.6.1", default-features = true }
num = { version = "0.2.0", default-features = false }
failure = { version = "0.1.3", optional = true }
euclidian-rythms = { git = "https://github.com/x37v/euclidian-rythm.git", optional = true}
libc = { version = "0.2.47" }
cfg-if = "0.1.6"
lazy_static = "1.3.0"
spin = "0.5.2"

[dev-dependencies]
jack = { git = "https://github.com/RustAudio/rust-jack.git" }
rosc = "~0.1"
heapless = "0.5.0"

#[[example]]
#name = "jack-client"
#required-features = ["std", "euclidean"]

[[example]]
name = "no_std"

#XXX for the no_std test, remove when not needed anymore
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


