[package]
name = "sched"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[features]
with_std = [ "xnor_llist", "failure", "with_alloc"]
with_alloc = []
with_euclidean = ["euclidian-rythms"]
default = ["with_std", "with_euclidean"]

[dependencies]
sched_macros = { git = "https://github.com/x37v/sched_macros.git" }
xnor_llist = { git = "https://github.com/x37v/rust-llist", branch = "develop", optional = true }
spinlock = { git = "https://github.com/x37v/rust-spinlock-mutex", branch = "develop" }
rand = { version = "0.6.1", default-features = true }
num = { version = "0.2.0", default-features = false }
failure = { version = "0.1.3", optional = true }
euclidian-rythms = { git = "https://github.com/x37v/euclidian-rythm.git", optional = true}
libc = { version = "0.2.47" }
cfg-if = "0.1.6"

[dev-dependencies]
jack = { git = "https://github.com/RustAudio/rust-jack.git" }
rosc = "~0.1"

[[example]]
name = "jack-client"
required-features = ["with_std", "euclidian"]

[[example]]
name = "no_std"
