[package]
name = "graph"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]

[dependencies]
spinlock = { git = "https://github.com/x37v/rust-spinlock-mutex", branch = "develop" }
xnor_llist = { git = "https://github.com/x37v/rust-llist", branch = "develop" }
